### ISSUE TITLE
transform.modify error

### ISSUE THREAD

**Issue by jmrichardson** [firmai/deltapy#4]
Hi,

This one does not find the function magnify.  I think it may be something to do with the tsaug package:

    df_out = transform.modify(df.copy(),["Close"]); df_out.head()

**Comment by abdallah1097** [comment]
@jmrichardson  any updates on how to solve this?

**Comment by jmrichardson** [comment]
@abdallah1097 ,  Sorry no response from the repo owner (should be archived)
